<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>FiestaKit - La mejor opci&oacute;n para tu fuesta</title>
		<meta name="author" content="Deyti, S.A. de C.V."/>
		<meta name="developer" content="Adolfo Morales<adolfo.morales@gmail.com>">
		<meta name="description" content="FiestaKit::Sitio de publicidad para fiestas"/>
		<meta http-equiv="expires" content="0"/>
		<meta name="Keywords" content="FiestaKit,fiesta,evento,men&uacute;alquiler;salones de fiestas;" />
		<meta name="ROBOTS" content="NOARCHIVE" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" href="/css/estilos.css" type="text/css" media="all">
		<link rel="stylesheet" href="/css/estilosE.css" type="text/css" media="all">
	</head>

	<body>
		<div id="page" class="internal-page">
				<div id="content">
					<?php echo $this->layout()->content ?>
				</div>

		</div>

<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="5" colspan="2"></td>
  </tr>
  <tr>
    <td width="686" height="29" background="/images/back-menu.jpg"><table width="400" height="31" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="30%" height="31"><div id="menuLinks"><a href="#">Inicio</a></div></td>
        <td width="34%" height="31"><div id="menuLinks"><a href="#">An&uacute;nciate</a></div></td>
        <td width="33%" height="31"><div id="menuLinks"><a href="#">Servicios </a></div></td>
      </tr>
    </table>
    </td>
    <td width="314" background="/images/back-menu.jpg"><div id="letras">Derechos reservados  FIESTAKIT.COM 2008</div></td>
  </tr>
</table>
<table width="500" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td valign="top"><div align="center"><img src=/images/"cierre.jpg" width="346" height="163" /></div></td>
  </tr>
  <tr>
    <td valign="top">&nbsp;</td>
  </tr>
</table>

	</body>
</html>
