<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->title ?></title>
		<meta name="author" content="MashedCode Co."/>
		<meta name="developer" content="Adolfo Morales<adolfo.morales@gmail.com>">
		<meta name="description" content="FiestaKit::Sitio de publicidad para fiestas"/>
		<meta http-equiv="expires" content="0"/>
		<meta name="Keywords" content="FiestaKit,fiesta,evento,men&uacute;alquiler;salones de fiestas;" />
		<meta name="ROBOTS" content="NOARCHIVE" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<!?[if IE 6]> <link href="/css/estilosE.css" rel="stylesheet" type="text/css" media="all" /> <![endif]?>
		<![if !IE]><link href="/css/estilos.css" rel="stylesheet" type="text/css" media="all" /><![endif]>
      <script type="text/JavaScript">
      <!--
			function MM_preloadImages() { //v3.0
				var d=document; if(d.images){ if(!d.MM_p) d.MM_p=new Array();
				var i,j=d.MM_p.length,a=MM_preloadImages.arguments; for(i=0; i<a.length; i++)
				if (a[i].indexOf("#")!=0){ d.MM_p[j]=new Image; d.MM_p[j++].src=a[i];}}
			}
		//-->
		</script>
	</head>

	<body>

<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#000000">
  <tr>
    <td><table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#000000">
      <tr>
        <td width="790" ><div align="left" class="topnegro">Directorio de productos y servicios para todo tipo de fiesta, evento o convenci&oacute;n</div></td>
        <td width="173" ><div align="right" class="topnegro">Presentes en todo M&eacute;xico </div></td>
        <td width="37" ><img src="/images/bandera.gif" width="26" height="25" /></td>
      </tr>
    </table>
    </td>
  </tr>
</table>
<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="168" colspan="2" background="/images/top.png">&nbsp;</td>
  </tr>
  <tr>
	 <td width="570" height="31" background="/images/back-menu.jpg">
      <table width="400" height="31" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="30%" height="31"><div id="menuLinks"><a href="/">Inicio</a></div></td>
          <td width="34%" height="31"><div id="menuLinks"><a href="/anunciate">An&uacute;nciate</a></div></td>
          <td width="33%" height="31"><div id="menuLinks"><a href="/servicios">Servicios </a></div></td>
        </tr>
		</table>
    </td>
    <td width="440" height="31" background="/images/back-menu.jpg" ><div id="letras">SERVICIOS  Y PRODUCTOS PARA TU FIESTA, EVENTO O CONVENCI&Oacute;N</div></td>
  </tr>
  <tr>
    <td height="5" colspan="2"></td>
  </tr>
</table>

		<div id="page" class="internal-page">
				<div id="content">
					<?php echo $this->layout()->content ?>
				</div>

		</div>

<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="5" colspan="2"></td>
  </tr>
  <tr>
    <td width="686" height="29" background="/images/back-menu.jpg"><table width="400" height="31" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="30%" height="31"><div id="menuLinks"><a href="/">Inicio</a></div></td>
        <td width="34%" height="31"><div id="menuLinks"><a href="/anunciate">An&uacute;nciate</a></div></td>
        <td width="33%" height="31"><div id="menuLinks"><a href="/servicios">Servicios </a></div></td>
      </tr>
    </table>
    </td>
    <td width="314" background="/images/back-menu.jpg"><div id="letras">Derechos reservados  FIESTAKIT.COM 2008</div></td>
  </tr>
</table>
<table width="500" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td valign="top"><div align="center"><img src=/images/"cierre.jpg" width="346" height="163" /></div></td>
  </tr>
  <tr>
    <td valign="top">&nbsp;</td>
  </tr>
</table>

	</body>
</html>
