<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" background="/images/back-page.png">
  <tr>
    <td width="13">&nbsp;</td>
    <td width="400" valign="top"><table width="400" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="txt">Obten los datos y referencias de los mejores proveedores de  servicios y productos para tu fiesta, evento o convenci&oacute;n, de cualquier parte de M&eacute;xico</div></td>
      </tr>
      <tr>
        <td><img src="/images/ninia.png" alt="" width="400" height="160" longdesc="fiesta evento boda 15 a&ntilde;os" /></td>
      </tr>
      <tr>
        <td><img src="/images/ninia2.png" alt="" width="400" height="43" longdesc="evento fiesta boda 15 a&ntilde;os convencion infantil" /></td>
      </tr>
      <tr>
        <td><table width="400" border="0" cellpadding="0" cellspacing="0" background="/images/ninia3.png">
          <tr>
				<td width="196" valign="top"><div id="list-menu">
              <ul>
              <!-- ?= $this->l_estados; ? -->
				  <li><a href="estado/ags">Aguascalientes</a></li>
              <li><a href="estado/bc">Baja California</a></li>
              <li><a href="estado/bcn">Baja California Sur</a></li>
              <li><a href="estado/chp">Chiapas</a></li>
              <li><a href="estado/chi">Chihuahua </a></li>
              <li><a href="estado/coa">Coahuila </a></li>
              <li><a href="estado/col">Colima </a></li>
              <li><a href="estado/df">Distrito Federal </a></li>
              <li><a href="estado/dur">Durango </a></li>
              <li><a href="estado/gua">Guanajuato </a></li>
              <li><a href="estado/gue">Guerrero </a></li>
              <li><a href="estado/hgo">Hidalgo </a></li>
              <li><a href="estado/jal">Jalisco</a></li>
              <li><a href="estado/mich">Michoac&aacute;n</a></li>
              <li><a href="estado/mor">Morelos </a></li>
              <li><a href="estado/mex">Estado de M&eacute;xico</a></li></ul></div>
            <td width="204" valign="top"><div id="list-menu"><ul><li><a href="#">Nayarit </a></li>
              <li><a href="estado/nl">Nuevo Le&oacute;n </a></li>
              <li><a href="estado/oax">Oaxaca</a></li>
              <li><a href="estado/pue">Puebla</a> </li>
              <li><a href="estado/que">Quer&eacute;taro </a></li>
              <li><a href="estado/qui">Quintana Roo</a></li>
              <li><a href="estado/slp">San Luis Potos&iacute; </a></li>
              <li><a href="estado/sin">Sinaloa </a></li>
              <li><a href="estado/son">Sonora </a></li>
			     <li><a href="estado/tab">Tabasco</a> </li>
              <li><a href="estado/tam">Tamaulipas</a></li>
              <li><a href="estado/tla">Tlaxcala</a></li>
              <li><a href="estado/ver">Veracruz </a></li>
              <li><a href="estado/yuc">Yucat&aacute;n </a></li>
				  <li><a href="estado/zac">Zacatecas</a></li>
            </ul></div></td>
          </tr>
        </table>
          <table width="400" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><img src="/images/ninia4.png" alt="" width="400" height="23" longdesc="boda evento fiesta convenci&oacute;n" /></td>
            </tr>
          </table></td>
      </tr>
    </table></td>
    <td width="28">&nbsp;</td>
    <td width="541" valign="top"><table width="538" height="20" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
      <table width="538" height="45" border="0" cellpadding="0" cellspacing="0" background="/images/back-buscador.jpg" style="border:solid #71828A 1px">
        <tr>
          <td width="538" height="60" class="txt2">Selecciona el servicio o producto <br />
          para tu fiesta, evento o convenci&oacute;n</td>
        </tr>
      </table>
      <table width="538" height="53" border="0" cellpadding="0" cellspacing="0" background="back-buscador2.jpg" style="border-bottom: 1px solid #71828A;
border-right: 1px solid #71828A;
border-left: 1px solid #71828A;">
        <tr>
          <td width="117"><div class="txt3">Estoy buscando:</div></td>
          <td width="152"><form name="form1" id="form1">
            <select name="menu1" class="txt4" onchange="MM_jumpMenu('parent',this,0)">
              <option value="#" selected="selected">Accesorios</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
            </select>
          </form></td>
          <td width="23"><div class="txt3">En:</div></td>
          <td width="159"><form name="form1" id="form1">
            <select name="select" class="txt4" onchange="MM_jumpMenu('parent',this,0)">
              <option value="#" selected="selected">Todo M&eacute;xico</option>
                <?= $this->c_estados; ?>
            </select>
          </form></td>
          <td width="87"><div align="center">
            <input type="submit" name="Submit" value="Buscar" />
          </div></td>
        </tr>
      </table>
      <table width="538" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>&nbsp;</td>
        </tr>
      </table>
      <table width="538" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="/images/necesitas1.png" alt="" width="538" height="55" longdesc="fiestas eventos convenciones" /></td>
        </tr>
        <tr>
          <td><table width="538" border="0" cellpadding="0" cellspacing="0" background="/images/necesitas2.png">
            <tr>
              <td valign="top" class="AB">A - B</td>
              <td valign="top" class="AB">C - F </td>
            </tr>
            <tr>
				  <td width="259" valign="top">
                <div id="list-menu2">
                  <ul>
                    <?= $this->categoria_ab; ?>
						</ul>
                </div>
                <div>
                  <div align="center"><img src="/images/divisor.gif" alt="fiestas" longdesc="eventos" /></div>
                </div>
                <div><span class="AB">G - M </span></div>
                <div id="list-menu2">
                  <ul>
                    <?= $this->categoria_gm; ?>
                  </ul>
					 </div>
              </td>
				  <td width="279" valign="top">
					 <div id="list-menu2">
                  <ul>
                    <?= $this->categoria_cf; ?>
                  </ul>
                </div>
                <div>
                  <div align="center"><img src="/images/divisor.gif" alt="fiestas" longdesc="eventos" /></div>
                </div>
                <div><span class="AB">N - Z </span></div>
                <div id="list-menu2">
                  <ul>
                    <?= $this->categoria_nz; ?>
					   </ul>
                </div>
              </td>
            </tr>
          </table></td>
        </tr>
        <tr>
          <td><table width="538" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td><img src="/images/necesitas3.png" alt="" width="538" height="33" longdesc="evento fiesta convencion" /></td>
                </tr>
            </table>
            <table width="538" height="20" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td>&nbsp;</td>
              </tr>
            </table></td>
        </tr>
      </table>
    </td>
    <td width="18">&nbsp;</td>
  </tr>
</table>

  </body>
</html>
