<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	 <title><?php echo $this->escape($this->title);?></title>
  </head>
  <body>

<table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#000000">
  <tr>
    <td><table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#000000">
      <tr>
        <td width="790" ><div align="left" class="topnegro">Directorio de productos y servicios para todo tipo de fiesta, evento o convenci&oacute;n</div></td>
        <td width="173" ><div align="right" class="topnegro">Presentes en todo M&eacute;xico </div></td>
        <td width="37" ><img src="/images/bandera.gif" width="26" height="25" /></td>
      </tr>
    </table>
    </td>
  </tr>
</table>
<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="168" colspan="2" background="/images/top.png">&nbsp;</td>
  </tr>
  <tr>
    <td width="570" height="31" background="/images/back-menu.jpg"><table width="400" height="31" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="30%" height="31"><div id="menuLinks"><a href="#">Inicio</a></div></td>
        <td width="34%" height="31"><div id="menuLinks"><a href="#">An&uacute;nciate</a></div></td>
        <td width="33%" height="31"><div id="menuLinks"><a href="#">Servicios </a></div></td>
      </tr>
    </table></td>
    <td width="440" height="31" background="/images/back-menu.jpg" ><div id="letras">SERVICIOS  Y PRODUCTOS PARA TU FIESTA, EVENTO O CONVENCI&Oacute;N</div></td>
  </tr>
  <tr>
    <td height="5" colspan="2"></td>
  </tr>
</table>
<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" background="/images/back-page.png">
  <tr>
    <td width="13">&nbsp;</td>
    <td width="400" valign="top"><table width="400" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="txt">Obten los datos y referencias de los mejores proveedores de  servicios y productos para tu fiesta, evento o convenci&oacute;n, de cualquier parte de M&eacute;xico</div></td>
      </tr>
      <tr>
        <td><img src="/images/ninia.png" alt="" width="400" height="160" longdesc="fiesta evento boda 15 a&ntilde;os" /></td>
      </tr>
      <tr>
        <td><img src="/images/ninia2.png" alt="" width="400" height="43" longdesc="evento fiesta boda 15 a&ntilde;os convencion infantil" /></td>
      </tr>
      <tr>
        <td><table width="400" border="0" cellpadding="0" cellspacing="0" background="/images/ninia3.png">
          <tr>
            <td width="196" valign="top"><div id="list-menu"><ul><li><a href="#">Aguascalientes</a></li>
              <li><a href="#">Baja California</a></li>
              <li><a href="#">Baja California Sur</a></li>
              <li><a href="#">Chiapas</a></li>
              <li><a href="#">Chihuahua </a></li>
              <li><a href="#">Coahuila </a></li>
              <li><a href="#">Colima </a></li>
              <li><a href="#">Distrito Federal </a></li>
              <li><a href="#">Durango </a></li>
              <li><a href="#">Guanajuato </a></li>
              <li><a href="#">Guerrero </a></li>
              <li><a href="#">Hidalgo </a></li>
              <li><a href="#">Jalisco</a></li>
              <li><a href="#">Michoac&aacute;n</a></li>
              <li><a href="#">Morelos </a></li>
              <li><a href="#">Estado de M&eacute;xico</a></li></ul></div>
            <td width="204" valign="top"><div id="list-menu"><ul><li><a href="#">Nayarit </a></li>
              <li><a href="#">Nuevo Le&oacute;n </a></li>
              <li><a href="#">Oaxaca</a></li>
              <li><a href="#">Puebla</a> </li>
              <li><a href="#">Quer&eacute;taro </a></li>
              <li><a href="#">Quintana Roo</a></li>
              <li><a href="#">San Luis Potos&iacute; </a></li>
              <li><a href="#">Sinaloa </a></li>
              <li><a href="#">Sonora </a></li>
			  <li><a href="#">Tabasco</a> </li>
              <li><a href="#">Tamaulipas</a></li>
              <li><a href="#">Tlaxcala</a></li>
              <li><a href="#">Veracruz </a></li>
              <li><a href="#">Yucat&aacute;n </a></li>
              <li><a href="#">Zacatecas</a></li></ul></div></td>
          </tr>
        </table>
          <table width="400" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><img src="/images/ninia4.png" alt="" width="400" height="23" longdesc="boda evento fiesta convenci&oacute;n" /></td>
            </tr>
          </table></td>
      </tr>
    </table></td>
    <td width="28">&nbsp;</td>
    <td width="541" valign="top"><table width="538" height="20" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td>&nbsp;</td>
      </tr>
    </table>
      <table width="538" height="45" border="0" cellpadding="0" cellspacing="0" background="/images/back-buscador.jpg" style="border:solid #71828A 1px">
        <tr>
          <td width="538" height="60" class="txt2">Selecciona el servicio o producto <br />
          para tu fiesta, evento o convenci&oacute;n</td>
        </tr>
      </table>
      <table width="538" height="53" border="0" cellpadding="0" cellspacing="0" background="back-buscador2.jpg" style="border-bottom: 1px solid #71828A;
border-right: 1px solid #71828A;
border-left: 1px solid #71828A;">
        <tr>
          <td width="117"><div class="txt3">Estoy buscando:</div></td>
          <td width="152"><form name="form1" id="form1">
            <select name="menu1" class="txt4" onchange="MM_jumpMenu('parent',this,0)">
              <option value="#" selected="selected">Accesorios</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
              <option value="#">Agencia de viajes</option>
            </select>
          </form></td>
          <td width="23"><div class="txt3">En:</div></td>
          <td width="159"><form name="form1" id="form1">
            <select name="select" class="txt4" onchange="MM_jumpMenu('parent',this,0)">
              <option value="#" selected="selected">Todo M&eacute;xico</option>
              <option value="#">Aguascalientes</option>
              <option value="#">Baja California Norte</option>
              <option value="#">Baja california Sur</option>
              <option value="#">Chiapas</option>
              <option value="#">Chihuahua</option>
              <option value="#">Coahuila</option>
              <option value="#">Colima</option>
              <option value="#">Distrito Federal </option>
              <option value="#">Durango</option>
              <option value="#">Guanajuato</option>
              <option value="#">Guerrero</option>
              <option value="#">Hidalgo</option>
              <option value="#">Jalisco</option>
              <option value="#">Michoac&aacute;n</option>
              <option value="#">Morelos</option>
              <option value="#">Estado de M&eacute;xico</option>
              <option value="#">Nayarit </option>
              <option value="#">Nuevo Le&oacute;n </option>
              <option value="#">Oaxaca</option>
            </select>
          </form></td>
          <td width="87"><div align="center">
            <input type="submit" name="Submit" value="Buscar" />
          </div></td>
        </tr>
      </table>
      <table width="538" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>&nbsp;</td>
        </tr>
      </table>
      <table width="538" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="/images/necesitas1.png" alt="" width="538" height="55" longdesc="fiestas eventos convenciones" /></td>
        </tr>
        <tr>
          <td><table width="538" border="0" cellpadding="0" cellspacing="0" background="/images/necesitas2.png">
            <tr>
              <td valign="top" class="AB">A - B</td>
              <td valign="top" class="AB">C - F </td>
            </tr>
            <tr>
              <td width="259" valign="top"><div id="list-menu2"><ul><li><a href="#">Accesorios</a> </li>
                  <li><a href="#">Agencia Viajes</a></li>
                  <li><a href="#">Agencias multiservicios</a></li>
                  <li><a href="#">Alquiler de automóviles</a></li>
                  <li><a href="#">Alquiler de manteler&iacute;a fina</a></li>
                  <li><a href="#">Alquiler de montaje</a></li>
                  <li><a href="#">Alquiler de trajes etiqueta</a></li>
                  <li><a href="#">Alquiler equipo audiovisual </a></li>
                  <li><a href="#">Alquiler equipo lounge</a></li>
                  <li><a href="#">Articulos para organizadores</a></li>
                  <li><a href="#">Audio e iluminación</a></li>
                  <li><a href="#">Banquetes a domicilio</a></li>
                  </ul></div>
                <div>
                  <div align="center"><img src="/images/divisor.gif" alt="fiestas" longdesc="eventos" /></div>
                </div>
                <div><span class="AB">G - M </span></div>
                <div id="list-menu2">
                  <ul>
                    <li><a href="#">Galletas</a> </li>
                    <li><a href="#">Grupos musicales</a></li>
                    <li><a href="#">Haciendas</a></li>
                    <li><a href="#">Imitadores</a></li>
                    <li><a href="#">Invitaciones</a></li>
                    <li><a href="#">Jard&iacute;nes</a></li>
                    <li><a href="#">Liberaci&oacute;n de mariposas</a></li>
                    <li><a href="#">Lugares: salones, jardines, museos, ex-haciendas...</a></li>
                    <li><a href="#">Maquillaje y Peinado</a></li>
                    <li><a href="#">Mariachis</a></li>
                    <li><a href="#">Moda y confecci&oacute;n</a></li>
                    <li><a href="#">M&uacute;sica de misa y cena</a></li>
                  </ul>
                </div></td>
              <td width="279" valign="top"><div id="list-menu2"><ul><li><a href="#">Calzado</a></li>
                  <li><a href="#">Cl&iacute;nicas de belleza</a></li>
                  <li><a href="#">Coordinadores de eventos</a></li>
                  <li><a href="#">Coreograf&iacute;as para XV A&ntilde;os</a> </li>
                  <li><a href="#">Coros</a></li>
                  <li><a href="#">Decoraci&oacute;n</a></li>
                  <li><a href="#">Disfrases</a></li>
                  <li><a href="#">DJ</a></li>
                  <li><a href="#">Esculturas de hielo</a></li>
                  <li><a href="#">Espect&aacute;culos</a> </li>
                  <li><a href="#">Fiestas tipo disco</a></li>
                  <li><a href="#">Fincas</a></li>
                  <li><a href="#">Florer&iacute;as</a></li>
                  <li><a href="#">Fotograf&iacute;a y video</a></li>
                <li><a href="#">Fuentes de Chocolate</a></li>
              </ul>
              </div>
                <div>
                  <div align="center"><img src="/images/divisor.gif" alt="fiestas" longdesc="eventos" /></div>
                </div>
                <div><span class="AB">N - Z </span></div>
                <div id="list-menu2">
                  <ul>
                    <li><a href="#">Novedades</a> </li>
                    <li><a href="#">Organizadores de eventos</a></li>
                    <li><a href="#">Orquestas de c&aacute;mara</a></li>
                    <li><a href="#">Pasteler&iacute;as</a></li>
                    <li><a href="#">Pirot&eacute;cnia</a></li>
                    <li><a href="#">Recuerdos</a></li>
                    <li><a href="#">Regalos</a></li>
                    <li><a href="#">Salones de belleza</a></li>
                    <li><a href="#">Salones de eventos</a></li>
                    <li><a href="#">Seguridad privada</a></li>
                    <li><a href="#">U&ntilde;as</a></li>
                    <li><a href="#">Vacaciones</a></li>
					<li><a href="#">Vestidos de:<br />
Novia, XV A&ntilde;os y Cocktail</a></li>
					<li><a href="#">Vinos y licores</a></li>
					</ul>
                </div></td>
            </tr>
          </table></td>
        </tr>
        <tr>
          <td><table width="538" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td><img src="/images/necesitas3.png" alt="" width="538" height="33" longdesc="evento fiesta convencion" /></td>
                </tr>
            </table>
            <table width="538" height="20" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td>&nbsp;</td>
              </tr>
            </table></td>
        </tr>
      </table>
    </td>
    <td width="18">&nbsp;</td>
  </tr>
</table>
<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td height="5" colspan="2"></td>
  </tr>
  <tr>
    <td width="686" height="29" background="/images/back-menu.jpg"><table width="400" height="31" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td width="30%" height="31"><div id="menuLinks"><a href="#">Inicio</a></div></td>
        <td width="34%" height="31"><div id="menuLinks"><a href="#">An&uacute;nciate</a></div></td>
        <td width="33%" height="31"><div id="menuLinks"><a href="#">Servicios </a></div></td>
      </tr>
    </table>
    </td>
    <td width="314" background="/images/back-menu.jpg"><div id="letras">Derechos reservados  FIESTAKIT.COM 2008</div></td>
  </tr>
</table>
<table width="500" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td valign="top"><div align="center"><img src=/images/"cierre.jpg" width="346" height="163" /></div></td>
  </tr>
  <tr>
    <td valign="top">&nbsp;</td>
  </tr>
</table>

  </body>
</html>
