<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" background="/images/back-page-2.gif">
  <tr>
    <td width="13">&nbsp;</td>
    <td width="296" valign="top"><table width="296" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="txt">Obten los datos y referencias de los mejores proveedores de  servicios y productos para tu fiesta, evento o convenci&oacute;n, en cualquier parte de M&eacute;xico</div></td>
      </tr>
      <tr>
        <td><img src="/images/nena.gif" width="296" height="210" /></td>
      </tr>
      <tr>
        <td background="/images/nena2.gif"><table width="296" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td valign="top" class="AB">A - B</td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Accesorios</a> </li>
                <li><a href="#">Agencia Viajes</a></li>
                <li><a href="#">Agencias multiservicios</a></li>
                <li><a href="#">Alquiler de autom&oacute;viles</a></li>
                <li><a href="#">Alquiler de manteler&iacute;a fina</a></li>
                <li><a href="#">Alquiler de montaje</a></li>
                <li><a href="#">Alquiler de trajes etiqueta</a></li>
                <li><a href="#">Alquiler equipo audiovisual </a></li>
                <li><a href="#">Alquiler equipo lounge</a></li>
                <li><a href="#">Articulos para organizadores</a></li>
                <li><a href="#">Audio e iluminaci&oacute;n</a></li>
                <li><a href="#">Banquetes a domicilio</a></li>
              </ul>
            </div>
              <div>
                <div align="center"><img src="/images/divisor2.gif" alt="fiestas" width="237" height="23" longdesc="eventos" /></div>
              </div></td>
          </tr>
          <tr>
            <td valign="top" class="AB">C - F </td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Calzado</a></li>
                <li><a href="#">Cl&iacute;nicas de belleza</a></li>
                <li><a href="#">Coordinadores de eventos</a></li>
                <li><a href="#">Coreograf&iacute;as para XV A&ntilde;os</a> </li>
                <li><a href="#">Coros</a></li>
                <li><a href="#">Decoraci&oacute;n</a></li>
                <li><a href="#">Disfrases</a></li>
                <li><a href="#">DJ</a></li>
                <li><a href="#">Esculturas de hielo</a></li>
                <li><a href="#">Espect&aacute;culos</a> </li>
                <li><a href="#">Fiestas tipo disco</a></li>
                <li><a href="#">Fincas</a></li>
                <li><a href="#">Florer&iacute;as</a></li>
                <li><a href="#">Fotograf&iacute;a y video</a></li>
                <li><a href="#">Fuentes de Chocolate</a></li>
              </ul>
            </div>
              <div>
                <div align="center"><img src="/images/divisor2.gif" alt="fiestas" width="237" height="23" longdesc="eventos" /></div>
              </div></td>
          </tr>
          <tr>
            <td><span class="AB">G - M </span></td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Galletas</a> </li>
                <li><a href="#">Grupos musicales</a></li>
                <li><a href="#">Haciendas</a></li>
                <li><a href="#">Imitadores</a></li>
                <li><a href="#">Invitaciones</a></li>
                <li><a href="#">Jard&iacute;nes</a></li>
                <li><a href="#">Liberaci&oacute;n de mariposas</a></li>
                <li><a href="#">Lugares: salones, jardines, museos, ex-haciendas...</a></li>
                <li><a href="#">Maquillaje y Peinado</a></li>
                <li><a href="#">Mariachis</a></li>
                <li><a href="#">Moda y confecci&oacute;n</a></li>
                <li><a href="#">M&uacute;sica de misa y cena</a></li>
              </ul>
            </div>
              <div>
                <div align="center"><img src="/images/divisor2.gif" alt="fiestas" width="237" height="23" longdesc="eventos" /></div>
              </div></td>
          </tr>
          <tr>
            <td><span class="AB">N - Z </span></td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Novedades</a> </li>
                <li><a href="#">Organizadores de eventos</a></li>
                <li><a href="#">Orquestas de c&aacute;mara</a></li>
                <li><a href="#">Pasteler&iacute;as</a></li>
                <li><a href="#">Pirot&eacute;cnia</a></li>
                <li><a href="#">Recuerdos</a></li>
                <li><a href="#">Regalos</a></li>
                <li><a href="#">Salones de belleza</a></li>
                <li><a href="#">Salones de eventos</a></li>
                <li><a href="#">Seguridad privada</a></li>
                <li><a href="#">U&ntilde;as</a></li>
                <li><a href="#">Vacaciones</a></li>
                <li><a href="#">Vestidos de:<br />
                  Novia, XV A&ntilde;os y Cocktail</a></li>
                <li><a href="#">Vinos y licores</a></li>
              </ul>
            </div></td>
          </tr>

        </table></td>
      </tr>
      <tr>
        <td><img src="/images/nena3.gif" width="296" height="26" /></td>
      </tr>
    </table>
      <table width="10" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>&nbsp;</td>
        </tr>
      </table></td>
    <td width="28">&nbsp;</td>
    <td valign="top"><table width="538" height="20" border="0" cellpadding="0" cellspacing="0">
      <tr>
        <td height="20"></td>
      </tr>
    </table>
      <table width="643" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td colspan="2"><img src="/images/anunciate-1.gif" width="643" height="50" /></td>
        </tr>
        <tr>
          <td colspan="2" align="center" bgcolor="#73848C" class="sieres" style="padding: 15px"><p>Si eres proveedor de servicios o productos para fiestas, eventos o convenciones, no lo dudes llena este sencillo cuestionario</p>          </td>
        </tr>
        <tr>
          <td colspan="2"><img src="/images/anunciate-2.gif" width="643" height="8" /></td>
        </tr>
        <tr>
          <td height="5" colspan="2" align="center"><img src="/images/orla.gif" width="270" height="26" vspace="15" /></td>
        </tr>
        <tr>
          <td height="5" align="left" class="titulante" style="padding: 0px 0px 5px 0px">Selecciona el tipo de anuncio</td>
          <td align="right" style="padding: 0px 0px 5px 0px" id="detalle"><a href="#">ver detalle de cada tipo de anuncio</a></td>
        </tr>
      </table>
      <table width="643" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><img src="/images/anunciate-3.gif" width="643" height="18" /></td>
        </tr>
      </table>
      <table width="643" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td valign="top">
            <form id="form1" name="form1" method="post" action="">
              <table width="643" border="0" cellpadding="0" cellspacing="0" background="/images/anunciate-back.gif">
                <tr>
                  <td width="150">&nbsp;</td>
                  <td width="195" align="center"><span class="ARIAL16">B&aacute;sico</span>
                    <label>
                    <input name="radiobutton" type="radio" value="radiobutton" />
                  </label></td>
                  <td width="107" align="center"><span class="ARIAL16">Avanzado</span>
                    <label>
                    <input name="radiobutton" type="radio" value="radiobutton" />
                  </label></td>
                  <td width="191" align="center"><span class="ARIAL16">Premium</span>
                    <label>
                    <input name="radiobutton" type="radio" value="radiobutton" />
                  </label></td>
                </tr>
                <tr>
                  <td colspan="4"><table width="599" border="1" align="center" cellpadding="4" cellspacing="0" bordercolor="#CCCCCC" bgcolor="#FFFFFF" class="coll">
                    <tr>
                      <td width="25%" align="right" class="ARIAL12">Ficha general</td>
                      <td width="25%" align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                      <td width="25%" align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                      <td width="25%" align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                    </tr>
                    <tr>
                      <td align="right" class="ARIAL12">Pagina Especial</td>
                      <td align="center"><img src="/images/cruz.gif" width="14" height="15" /></td>
                      <td align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                      <td align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                    </tr>
                    <tr>
                      <td align="right" class="ARIAL12">Ficha con resalte</td>
                      <td align="center"><img src="/images/cruz.gif" width="14" height="15" /></td>
                      <td align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                      <td align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                    </tr>
                    <tr>
                      <td align="right" class="ARIAL12">Banner en Home</td>
                      <td align="center"><img src="/images/cruz.gif" width="14" height="15" /></td>
                      <td align="center"><img src="/images/cruz.gif" width="14" height="15" /></td>
                      <td align="center"><img src="/images/paloma.gif" width="16" height="15" /></td>
                    </tr>
                    <tr>
                      <td align="right" class="ARIAL12">Costo por a&ntilde;o</td>
                      <td align="center" class="ARIAL12">$300 mn</td>
                      <td align="center" class="ARIAL12">$700 mn</td>
                      <td align="center" class="ARIAL12">$1000 mn</td>
                    </tr>
                  </table></td>
                </tr>
                <tr>
                  <td height="10" colspan="4"></td>
                </tr>
              </table>
              <table width="643" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td><img src="/images/anunciate-4.gif" width="643" height="10" /></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                </tr>
                <tr>
                  <td class="titulante" style="padding: 0px 0px 5px 0px">Datos del anuncio</td>
                </tr>
                <tr>
                  <td><img src="/images/anunciate-3.gif" width="643" height="18" /></td>
                </tr>
              </table>
              <table width="643" border="0" cellpadding="0" cellspacing="7" background="/images/anunciate-back.gif">
                <tr>
                  <td width="230" align="right"><span class="asterisco">*</span><span class="trebuchet">Nombre de la empresa o negocio:</span></td>
                  <td width="413"><input name="textfield" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Cuenta de correo del negocio:</span></td>
                  <td><input name="textfield22" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Tel&eacute;fono del negocio:</span></td>
                  <td><input name="textfield2" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Estado de la Rep&uacute;blica:</span></td>
                  <td><label>
                    <select name="select2">
                      <option>Distrito Federal</option>
                    </select>
                  </label></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Delegaci&oacute;n o municipio:</span></td>
                  <td><select name="select3">
                    <option>Benito Juarez</option>
                                                      </select></td>
                </tr>
                <tr>
                  <td align="right" valign="top"><span class="asterisco">*</span><span class="trebuchet">Direcci&oacute;n:<br />
                  </span><span class="ARIAL10">100 car&aacute;cteres m&aacute;ximo</span> </td>
                  <td valign="top"><textarea name="textfield5" cols="55" rows="2" class="trebuchet11pix"></textarea></td>
                </tr>
                <tr>
                  <td align="right" valign="top"><span class="asterisco">*</span><span class="trebuchet">&iquest;En qu&eacute; categor&iacute;a te ubicar&iacute;as?:</span></td>
                  <td><select name="select" size="1" class="trebuchet11pix">
                    <option selected="selected">Selecciona una categor&iacute;a</option>
                    <option value="Accesorios">Accesorios</option>
                    <option>Agencia de Viajes</option>
                  </select></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Logotipo de tu negocio:</span></td>
                  <td><label>
                    <input name="textfield103" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                    <input type="submit" name="Submit" value="Seleccionar archivo" />
                  </label></td>
                </tr>
                <tr>
                  <td align="right"><span class="trebuchet">Propon una categor&iacute;a nueva:</span></td>
                  <td><input name="textfield42" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td colspan="2" align="left" style="padding: 15px 5px 0px 20px"><span class="asterisco">*</span><span class="trebuchet">Resumen o descripci&oacute;n de los productos y/o servicios:</span></td>
                </tr>
                <tr>
                  <td align="right" valign="top"><span class="ARIAL10">120 car&aacute;cteres m&aacute;ximo</span></td>
                  <td><textarea name="textfield8" cols="55" rows="4" class="trebuchet11pix"></textarea></td>
                </tr>

                <tr>
                  <td colspan="2" style="padding: 5px 5px 0px 20px"><span class="asterisco">*</span><span class="trebuchet">Descripci&oacute;n larga de los productos y/o servicios:</span></td>
                </tr>
                <tr>
                  <td align="right" valign="top"><span class="ARIAL10">600 car&aacute;cteres m&aacute;ximo</span></td>
                  <td ><textarea name="textarea" cols="55" rows="8" class="trebuchet11pix"></textarea></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet">Fotograf&iacute;as:</td>
                  <td >&nbsp;</td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 1: </td>
                  <td ><input name="textfield104" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit2" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 2: </td>
                  <td ><input name="textfield105" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit3" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 3: </td>
                  <td ><input name="textfield106" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit4" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 4: </td>
                  <td ><input name="textfield107" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit5" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 5: </td>
                  <td ><input name="textfield108" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit6" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 6: </td>
                  <td ><input name="textfield109" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit7" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 7: </td>
                  <td ><input name="textfield1010" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit8" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 8: </td>
                  <td ><input name="textfield1011" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit9" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 9: </td>
                  <td ><input name="textfield1012" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit10" value="Seleccionar archivo" /></td>
                </tr>
                <tr>
                  <td align="right" valign="top" class="trebuchet11pix">Foto 10: </td>
                  <td ><input name="textfield102" type="text" class="trebuchet11pix" size="40" maxlength="40" />
                  <input type="submit" name="Submit11" value="Seleccionar archivo" /></td>
                </tr>
              </table>
              <table width="643" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td><img src="/images/anunciate-4.gif" width="643" height="10" /></td>
                </tr>
              </table>
              <table width="643" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td>&nbsp;</td>
                </tr>
                <tr>
                  <td class="titulante" style="padding: 0px 0px 5px 0px">Datos del usuario registrante:</td>
                </tr>
                <tr>
                  <td><img src="/images/anunciate-3.gif" width="643" height="18" /></td>
                </tr>
              </table>
              <table width="643" border="0" cellpadding="0" cellspacing="7" background="/images/anunciate-back.gif">
                <tr>
                  <td width="221" align="right"><span class="asterisco">*</span><span class="trebuchet">Nombre:</span></td>
                  <td colspan="2"><input name="textfield4" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Apellido paterno:</span></td>
                  <td colspan="2"><input name="textfield6" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Apellido materno:</span></td>
                  <td colspan="2"><input name="textfield7" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">E-mail:</span></td>
                  <td colspan="2"><input name="textfield9" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td align="right"><span class="asterisco">*</span><span class="trebuchet">Tel&eacute;fono (fijo):</span></td>
                  <td colspan="2"><input name="textfield10" type="text" class="trebuchet11pix" size="40" maxlength="40" /></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td width="127"><img src="/images/antispam.gif" width="125" height="40" /></td>
                  <td width="267"><input name="textfield1013" type="text" class="trebuchet11pix" size="15" maxlength="5" />
                  <br />
                  <span class="ARIAL10">Escribe los car&aacute;cteres anti-spam</span></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td colspan="2"><table width="200" border="1" cellpadding="5" cellspacing="0" bordercolor="#003366" bgcolor="#FFFFFF" class="coll">
                    <tr>
                      <td><label>
                        <input type="checkbox" name="checkbox" value="checkbox" />
                        <span class="trebuchet12">Acepto las</span> <span id="detalle"><a href="#">condiciones</a></span> </label></td>
                    </tr>
                  </table></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td colspan="2"><a href="#" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image11','','anunciate-6.gif',1)"><img src="/images/anunciate-5.gif" name="Image11" width="113" height="39" border="0" id="Image11" /></a></td>
                </tr>
              </table>
              <table width="643" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td><img src="/images/anunciate-4.gif" width="643" height="10" /></td>
                </tr>
                <tr>
                  <td>&nbsp;</td>
                </tr>
                <tr>
                  <td class="trebuchet">Fiestakit.com es un directorio de promoci&oacute;n publicitaria, en ningun momento hacemos uso de tu informaci&oacute;n con fines distintos al de la promoci&oacute;n de tus servicios y/o productos dentro de Fiestakit.com, tampoco ponemos a disposici&oacute;n de terceros la informaci&oacute;n que nos proporciones.</td>
                </tr>
                <tr>
                  <td class="trebuchet">&nbsp;</td>
                </tr>
              </table>
            </form>
          </td>
        </tr>
      </table>
    </td>
    <td>&nbsp;</td>
  </tr>
</table>
