<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" background="/images/back-page-2.gif">
  <tr>
    <td width="13">&nbsp;</td>
    <td width="296" valign="top"><table width="296" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><div class="txt">Obten los datos y referencias de los mejores proveedores de  servicios y productos para tu fiesta, evento o convenci&oacute;n, de cualquier parte de M&eacute;xico</div></td>
      </tr>
      <tr>
        <td><img src="/images/nena.gif" width="296" height="210" /></td>
      </tr>
      <tr>
        <td background="/images/nena2.gif"><table width="296" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td valign="top" class="AB">A - B</td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Accesorios</a> </li>
                <li><a href="#">Agencia Viajes</a></li>
                <li><a href="#">Agencias multiservicios</a></li>
                <li><a href="#">Alquiler de autom&oacute;viles</a></li>
                <li><a href="#">Alquiler de manteler&iacute;a fina</a></li>
                <li><a href="#">Alquiler de montaje</a></li>
                <li><a href="#">Alquiler de trajes etiqueta</a></li>
                <li><a href="#">Alquiler equipo audiovisual </a></li>
                <li><a href="#">Alquiler equipo lounge</a></li>
                <li><a href="#">Articulos para organizadores</a></li>
                <li><a href="#">Audio e iluminaci&oacute;n</a></li>
                <li><a href="#">Banquetes a domicilio</a></li>
              </ul>
            </div>
              <div>
                <div align="center"><img src="/images/divisor2.gif" alt="fiestas" width="237" height="23" longdesc="eventos" /></div>
              </div></td>
          </tr>
          <tr>
            <td valign="top" class="AB">C - F </td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Calzado</a></li>
                <li><a href="#">Cl&iacute;nicas de belleza</a></li>
                <li><a href="#">Coordinadores de eventos</a></li>
                <li><a href="#">Coreograf&iacute;as para XV A&ntilde;os</a> </li>
                <li><a href="#">Coros</a></li>
                <li><a href="#">Decoraci&oacute;n</a></li>
                <li><a href="#">Disfrases</a></li>
                <li><a href="#">DJ</a></li>
                <li><a href="#">Esculturas de hielo</a></li>
                <li><a href="#">Espect&aacute;culos</a> </li>
                <li><a href="#">Fiestas tipo disco</a></li>
                <li><a href="#">Fincas</a></li>
                <li><a href="#">Florer&iacute;as</a></li>
                <li><a href="#">Fotograf&iacute;a y video</a></li>
                <li><a href="#">Fuentes de Chocolate</a></li>
              </ul>
            </div>
              <div>
                <div align="center"><img src="/images/divisor2.gif" alt="fiestas" width="237" height="23" longdesc="eventos" /></div>
              </div></td>
          </tr>
          <tr>
            <td><span class="AB">G - M </span></td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Galletas</a> </li>
                <li><a href="#">Grupos musicales</a></li>
                <li><a href="#">Haciendas</a></li>
                <li><a href="#">Imitadores</a></li>
                <li><a href="#">Invitaciones</a></li>
                <li><a href="#">Jard&iacute;nes</a></li>
                <li><a href="#">Liberaci&oacute;n de mariposas</a></li>
                <li><a href="#">Lugares: salones, jardines, museos, ex-haciendas...</a></li>
                <li><a href="#">Maquillaje y Peinado</a></li>
                <li><a href="#">Mariachis</a></li>
                <li><a href="#">Moda y confecci&oacute;n</a></li>
                <li><a href="#">M&uacute;sica de misa y cena</a></li>
              </ul>
            </div>
              <div>
                <div align="center"><img src="/images/divisor2.gif" alt="fiestas" width="237" height="23" longdesc="eventos" /></div>
              </div></td>
          </tr>
          <tr>
            <td><span class="AB">N - Z </span></td>
          </tr>
          <tr>
            <td><div id="list-menu3">
              <ul>
                <li><a href="#">Novedades</a> </li>
                <li><a href="#">Organizadores de eventos</a></li>
                <li><a href="#">Orquestas de c&aacute;mara</a></li>
                <li><a href="#">Pasteler&iacute;as</a></li>
                <li><a href="#">Pirot&eacute;cnia</a></li>
                <li><a href="#">Recuerdos</a></li>
                <li><a href="#">Regalos</a></li>
                <li><a href="#">Salones de belleza</a></li>
                <li><a href="#">Salones de eventos</a></li>
                <li><a href="#">Seguridad privada</a></li>
                <li><a href="#">U&ntilde;as</a></li>
                <li><a href="#">Vacaciones</a></li>
                <li><a href="#">Vestidos de:<br />
                  Novia, XV A&ntilde;os y Cocktail</a></li>
                <li><a href="#">Vinos y licores</a></li>
              </ul>
            </div></td>
          </tr>

        </table></td>
      </tr>
      <tr>
        <td><img src="/images/nena3.gif" width="296" height="26" /></td>
      </tr>
    </table>
      <table width="10" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td>&nbsp;</td>
        </tr>
      </table></td>
    <td width="28">&nbsp;</td>
    <td valign="top"><table width="644" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td align="center"><img src="/images/orla.gif" width="270" height="26" vspace="12" /></td>
        </tr>
        <tr>
          <td><p class="titulante">Pagina de acceso<br />
              <br />
              <span class="trebuchet">Para acceder a modificar tu anuncio deberas accesar con tu login y tu password,(tu login es tu cuenta de correo completa) el password te fue enviado por correo.</span><br />
          </p>
          </td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td align="center"><table width="400" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td><img src="/images/top-login.gif" width="400" height="8" /></td>
            </tr>
            <tr>
              <td><table width="400" border="0" cellpadding="0" cellspacing="5" bgcolor="#FFF39F" style="border-left:1px solid #cccccc; border-right:1px solid #cccccc">
                <tr>
                  <td width="151" align="right" class="txt">Login:</td>
                  <td width="234"><input name="user" type="text" value="" /></td>
                </tr>
                <tr>
                  <td align="right" class="txt">Password:</td>
						<td><input name="password" id="password" type="password" value="" /></td>
                </tr>
                <tr>
						<td colspan="2"><span style="position:relative;left:148px"> <input type="submit" name="btn-entrar" value="Entrar" background-image=url("/images/btn-entrar.gif") width="113" height="40" /></span></td>
                  </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td><span class="trebuchet11pix">Si olvidaste tu password da click</span> <span class="ixx"><a href="#">aqui</a></span></td>
                </tr>
              </table></td>
            </tr>
            <tr>
              <td><img src="/images/bottom-login.gif" width="400" height="8" /></td>
            </tr>
          </table></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
        </tr>
      </table>
  </table>
